name: Publish Python Package

on:
  push:
    tags:
      - 'v*'   # triggers on version tags like v0.1.0

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Get OIDC token
        id: oidc
        run: echo "OIDC token ready"

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ steps.oidc.outputs.token }}
        run: twine upload dist/*
